/**
 * Script para IMPORTAR dados dos PDFs para o Supabase
 * ====================================================
 * 
 * Como usar:
 * 1. Configure SUPABASE_URL e SUPABASE_KEY abaixo
 * 2. Rode: node importar-pdfs.js
 */

const SUPABASE_URL = 'https://qffnlznnkercxufbfple.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZm5sem5ua2VyY3h1ZmJmcGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM2ODU2MjEsImV4cCI6MjA5OTI2MTYyMX0.HU0gbXM_oMrHytqT-uR5pezWpzbHh7GlINP8zLZndjA';

const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// =========================================
// DADOS EXTRAÍDOS DOS PDFS
// =========================================

const clientes = [
  { nome: "Julio Cesar", cpf_cnpj: "951.876.69-00" },
  { nome: "Thamires R", cpf_cnpj: "538.093.34-00" },
  { nome: "consumido", cpf_cnpj: "" },
  { nome: "Edivau Ber", cpf_cnpj: "086.906.23-00" },
  { nome: "Marcio Gle", cpf_cnpj: "299.357.64-00" },
  { nome: "Ederson Ol", cpf_cnpj: "263.710.97-00" },
  { nome: "Jorge Luis", cpf_cnpj: "037.926.55-00" },
  { nome: "Gilberto M", cpf_cnpj: "308.266.51-00" },
  { nome: "José Luís G", cpf_cnpj: "097.140.40-00" },
  { nome: "Paulo Cesa", cpf_cnpj: "296.456.22-00" },
  { nome: "Armando B", cpf_cnpj: "127.983.33-00" },
  { nome: "Rosildo zal", cpf_cnpj: "266.855.00-00" },
  { nome: "Alexandre", cpf_cnpj: "224.162.70-00" },
  { nome: "Gesuele Fa", cpf_cnpj: "027.320.77-00" },
  { nome: "Aparecido", cpf_cnpj: "103.659.16-00" },
  { nome: "Antônio Pe", cpf_cnpj: "089.215.15-00" },
  { nome: "Israel Leite", cpf_cnpj: "221.599.42-00" },
  { nome: "Luiz Serafim", cpf_cnpj: "059.356.59-00" },
  { nome: "Marcio Ma", cpf_cnpj: "286.802.25-00" },
  { nome: "Bruno da S", cpf_cnpj: "443.931.18-00" },
  { nome: "Ronaldo Fe", cpf_cnpj: "370.846.41-00" },
  { nome: "Bartolome", cpf_cnpj: "007.830.40-00" },
  { nome: "Sergio Felix", cpf_cnpj: "" },
  { nome: "Adriana do", cpf_cnpj: "340.255.56-00" },
  { nome: "Michael Do", cpf_cnpj: "472.152.46-00" },
  { nome: "Valdir Afon", cpf_cnpj: "082.996.88-00" },
  { nome: "Antonio Ro", cpf_cnpj: "173.464.92-00" },
  { nome: "João Batist", cpf_cnpj: "748.931.65-00" },
  { nome: "Fabio Roch", cpf_cnpj: "447.925.85-00" },
  { nome: "Jose Salmo", cpf_cnpj: "379.290.53-00" },
  { nome: "Claudinei d", cpf_cnpj: "299.843.45-00" },
  { nome: "Cristiano Jo", cpf_cnpj: "347.325.76-00" },
  { nome: "Paulo Jose", cpf_cnpj: "008.602.15-00" },
  { nome: "Anderson E", cpf_cnpj: "275.595.70-00" },
  { nome: "Jose Claud", cpf_cnpj: "310.792.02-00" },
  { nome: "Luiz Alfred", cpf_cnpj: "222.114.00-00" },
  { nome: "Gabriele Th", cpf_cnpj: "481.614.25-00" },
  { nome: "Janaina Me", cpf_cnpj: "404.757.74-00" },
  { nome: "Joab Alves", cpf_cnpj: "311.504.72-00" },
  { nome: "Felipe Muz", cpf_cnpj: "500.800.94-00" },
  { nome: "Almirindo M", cpf_cnpj: "055.214.89-00" },
  { nome: "Jose Elder", cpf_cnpj: "345.632.49-00" },
  { nome: "Maria Elen", cpf_cnpj: "297.624.88-00" },
  { nome: "Celio Luis d", cpf_cnpj: "067.191.07-00" },
  { nome: "Everton Pin", cpf_cnpj: "427.847.38-00" },
  { nome: "Jenivaldo A", cpf_cnpj: "047.350.62-00" },
  { nome: "Petrucio Co", cpf_cnpj: "701.323.72-00" },
  { nome: "Leandro Ni", cpf_cnpj: "278.463.87-00" },
  { nome: "Arlindo Sou", cpf_cnpj: "083.002.18-00" },
  { nome: "Jose Soare", cpf_cnpj: "078.862.18-00" },
  { nome: "Rubens San", cpf_cnpj: "302.944.85-00" },
  { nome: "Walis da Si", cpf_cnpj: "243.293.21-00" },
  { nome: "Francisco L", cpf_cnpj: "001.504.88-00" },
  { nome: "Stive Cardo", cpf_cnpj: "348.056.34-00" },
  { nome: "Marcos Vin", cpf_cnpj: "417.323.43-00" },
  { nome: "Andre Luis", cpf_cnpj: "198.650.33-00" },
  { nome: "Leticia Ada", cpf_cnpj: "369.005.38-00" },
  { nome: "Claudemir", cpf_cnpj: "307.281.06-00" },
  { nome: "Everton Go", cpf_cnpj: "417.390.53-00" },
  { nome: "Renan da S", cpf_cnpj: "456.354.65-00" },
  { nome: "Angelica A", cpf_cnpj: "307.965.67-00" },
  { nome: "Cassiano d", cpf_cnpj: "050.533.85-00" },
  { nome: "Alison Mes", cpf_cnpj: "228.490.09-00" },
  { nome: "Ronaldo Ar", cpf_cnpj: "297.967.00-00" },
  { nome: "Cicera Stef", cpf_cnpj: "628.105.54-00" },
  { nome: "Alex Valeri", cpf_cnpj: "" },
  { nome: "Bruno Azar", cpf_cnpj: "453.870.92-00" },
  { nome: "Maisom Ap", cpf_cnpj: "499.972.28-00" },
  { nome: "Mirley Mes", cpf_cnpj: "405.120.06-00" },
  { nome: "Edson Reis", cpf_cnpj: "190.697.55-00" },
  { nome: "Ezequiel da", cpf_cnpj: "410.247.14-00" },
  { nome: "Carlos Elde", cpf_cnpj: "318.819.85-00" },
  { nome: "Camila Alv", cpf_cnpj: "395.802.69-00" },
  { nome: "Daniel Pere", cpf_cnpj: "179.126.31-00" },
  { nome: "Gustavo An", cpf_cnpj: "512.114.36-00" },
  { nome: "Claudio Ca", cpf_cnpj: "042.178.82-00" },
  { nome: "Sirineu Pai", cpf_cnpj: "147.019.17-00" },
  { nome: "Gilberto Si", cpf_cnpj: "027.517.72-00" },
  { nome: "Paulo Serg", cpf_cnpj: "076.257.59-00" },
  { nome: "Gerson de", cpf_cnpj: "310.721.62-00" },
  { nome: "Roberto Ba", cpf_cnpj: "314.370.55-00" },
  { nome: "Gilberto Al", cpf_cnpj: "319.514.79-00" },
  { nome: "Izaias Cost", cpf_cnpj: "347.593.97-00" },
  { nome: "Caio Evand", cpf_cnpj: "510.395.69-00" },
  { nome: "Rodrigo Gu", cpf_cnpj: "271.393.24-00" },
  { nome: "Igor Rodrig", cpf_cnpj: "330.148.15-00" },
  { nome: "Jose Rober", cpf_cnpj: "090.194.47-00" },
  { nome: "João Carlos", cpf_cnpj: "207.926.50-00" },
  { nome: "Paulo Robe", cpf_cnpj: "198.472.57-00" },
  { nome: "Arnaldo Pio", cpf_cnpj: "095.091.37-00" },
  { nome: "Rubens Silv", cpf_cnpj: "325.100.82-00" },
  { nome: "Jose Maria", cpf_cnpj: "027.277.34-00" },
  { nome: "Mario And", cpf_cnpj: "578.128.71-00" },
  { nome: "Milton Vila", cpf_cnpj: "639.663.52-00" },
  { nome: "Jose Loure", cpf_cnpj: "333.301.62-00" },
  { nome: "Jessica Fer", cpf_cnpj: "417.300.45-00" },
  { nome: "Reginaldo", cpf_cnpj: "114.415.29-00" },
  { nome: "Adriano da", cpf_cnpj: "299.711.03-00" },
  { nome: "Beijamim E", cpf_cnpj: "142.041.77-00" },
  { nome: "Edson Luis", cpf_cnpj: "127.528.77-00" },
  { nome: "Gilberto Fe", cpf_cnpj: "258.575.19-00" },
  { nome: "Valter Luiz", cpf_cnpj: "179.121.85-00" },
  { nome: "Adão Barb", cpf_cnpj: "733.335.81-00" },
  { nome: "Elma Santo", cpf_cnpj: "297.349.30-00" },
  { nome: "Vilson Tied", cpf_cnpj: "025.462.18-00" },
  { nome: "Clodoaldo", cpf_cnpj: "657.378.55-00" },
  { nome: "Rodrigo Ale", cpf_cnpj: "288.505.98-00" },
  { nome: "Bruno Nun", cpf_cnpj: "355.168.13-00" },
  { nome: "Luis Santos", cpf_cnpj: "108.546.67-00" },
  { nome: "Anderson d", cpf_cnpj: "473.884.65-00" },
  { nome: "Leonardo d", cpf_cnpj: "266.993.06-00" },
  { nome: "Denis Silva", cpf_cnpj: "498.447.91-00" },
  { nome: "Diego torre", cpf_cnpj: "425.378.23-00" },
  { nome: "Jean Pericl", cpf_cnpj: "329.472.19-00" },
  { nome: "Abraão Go", cpf_cnpj: "061.451.34-00" },
  { nome: "José Sirino", cpf_cnpj: "902.351.85-00" },
  { nome: "Hamilton V", cpf_cnpj: "639.663.52-00" },
  { nome: "Marcio Tei", cpf_cnpj: "071.515.31-00" },
  { nome: "Sidnei Rod", cpf_cnpj: "341.872.64-00" },
  { nome: "Barbara As", cpf_cnpj: "469.247.33-00" },
  { nome: "Siro Augus", cpf_cnpj: "316.441.53-00" },
  { nome: "Washingto", cpf_cnpj: "336.111.10-00" },
  { nome: "Nelson Gab", cpf_cnpj: "169.057.34-00" },
  { nome: "Renato de", cpf_cnpj: "276.400.61-00" },
  { nome: "Donizete F", cpf_cnpj: "055.507.53-00" },
  { nome: "Adenilson J", cpf_cnpj: "329.972.66-00" },
  { nome: "Lucio Mau", cpf_cnpj: "156.552.73-00" },
  { nome: "Julio Cezar", cpf_cnpj: "253.181.58-00" },
  { nome: "Thiago Aug", cpf_cnpj: "354.987.67-00" },
  { nome: "Bento Jose", cpf_cnpj: "104.002.23-00" },
  { nome: "João batist", cpf_cnpj: "057.776.96-00" },
  { nome: "José Evera", cpf_cnpj: "740.063.39-00" },
  { nome: "Manoel Be", cpf_cnpj: "075.244.45-00" },
  { nome: "Daniele Dia", cpf_cnpj: "418.987.20-00" },
  { nome: "Hellen Vida", cpf_cnpj: "497.840.23-00" },
  { nome: "Degair Jose", cpf_cnpj: "" },
  { nome: "Francisco a", cpf_cnpj: "" },
  { nome: "Adriano Lu", cpf_cnpj: "" },
  { nome: "José Milton", cpf_cnpj: "" },
  { nome: "Paulo Henr", cpf_cnpj: "" },
  { nome: "Vanderson", cpf_cnpj: "" },
  { nome: "Douglas Ap", cpf_cnpj: "" },
  { nome: "Marcelo Da", cpf_cnpj: "" },
  { nome: "Edson B. C", cpf_cnpj: "" },
  { nome: "Hamilton A", cpf_cnpj: "" },
  { nome: "Adriano An", cpf_cnpj: "" },
  { nome: "Eduardo Ba", cpf_cnpj: "" },
  { nome: "Geraldo M", cpf_cnpj: "" },
  { nome: "Elisandra d", cpf_cnpj: "" },
  { nome: "André Luis", cpf_cnpj: "" },
  { nome: "Junior Traja", cpf_cnpj: "" },
  { nome: "Paulo Luis", cpf_cnpj: "" },
  { nome: "Yasmin Ga", cpf_cnpj: "" },
  { nome: "Railton Agu", cpf_cnpj: "" },
  { nome: "Danilo de O", cpf_cnpj: "" },
  { nome: "Robson Vit", cpf_cnpj: "" },
  { nome: "Diego Mar", cpf_cnpj: "" },
  { nome: "João Gualb", cpf_cnpj: "" },
  { nome: "Rafael Diom", cpf_cnpj: "" },
  { nome: "Inair de So", cpf_cnpj: "" },
  { nome: "Doriel Sant", cpf_cnpj: "" },
  { nome: "Paulino Pe", cpf_cnpj: "" },
  { nome: "Francisco P", cpf_cnpj: "" },
  { nome: "Moises de", cpf_cnpj: "" },
  { nome: "Weber Con", cpf_cnpj: "" },
  { nome: "Leonardo N", cpf_cnpj: "" },
  { nome: "Eliel da Luz", cpf_cnpj: "" },
  { nome: "Edilaine de", cpf_cnpj: "" },
  { nome: "Divanildo d", cpf_cnpj: "" },
  { nome: "Edilmo Ma", cpf_cnpj: "" },
  { nome: "Carlos Edu", cpf_cnpj: "" },
  { nome: "Luis Augus", cpf_cnpj: "" },
  { nome: "José Libani", cpf_cnpj: "" },
  { nome: "Fernando d", cpf_cnpj: "" },
  { nome: "Ivan dos Sa", cpf_cnpj: "" },
  { nome: "Aldriano M", cpf_cnpj: "" },
  { nome: "Luis Fernan", cpf_cnpj: "" },
  { nome: "Edgar de S", cpf_cnpj: "" },
  { nome: "Osmar dos", cpf_cnpj: "" },
  { nome: "Cleiton Teo", cpf_cnpj: "" },
  { nome: "Marcos Au", cpf_cnpj: "" },
  { nome: "Aline Prisci", cpf_cnpj: "" },
  { nome: "Rafael Mor", cpf_cnpj: "" },
  { nome: "Claudio Dia", cpf_cnpj: "" },
  { nome: "Renato Ap", cpf_cnpj: "" },
  { nome: "Edilson Oliv", cpf_cnpj: "" },
  { nome: "Damião de", cpf_cnpj: "" },
  { nome: "Antonio M", cpf_cnpj: "" },
  { nome: "Andre Vale", cpf_cnpj: "" },
  { nome: "Marcos Alb", cpf_cnpj: "" },
  { nome: "Felipe Sant", cpf_cnpj: "" },
  { nome: "Lucas de O", cpf_cnpj: "" },
  { nome: "Adriano Nu", cpf_cnpj: "" },
  { nome: "Thomaz Az", cpf_cnpj: "" },
  { nome: "Jeferson Fi", cpf_cnpj: "" },
  { nome: "Regilson Jo", cpf_cnpj: "" },
  { nome: "Kauan Alve", cpf_cnpj: "" },
  { nome: "Vitor Perei", cpf_cnpj: "" },
  { nome: "Silvio José", cpf_cnpj: "" },
  { nome: "Jean Robso", cpf_cnpj: "" },
  { nome: "Emerson P", cpf_cnpj: "" },
  { nome: "Vebersom", cpf_cnpj: "" },
  { nome: "Gilmara Jo", cpf_cnpj: "" },
  { nome: "Luis Carlos", cpf_cnpj: "" },
  { nome: "Alane da C", cpf_cnpj: "" },
  { nome: "José Uever", cpf_cnpj: "" },
  { nome: "Rafael Pint", cpf_cnpj: "" },
  { nome: "Jose Helton", cpf_cnpj: "" },
  { nome: "Djalma de", cpf_cnpj: "" },
  { nome: "Cesar Augu", cpf_cnpj: "" },
  { nome: "Gilberto Jo", cpf_cnpj: "" },
  { nome: "Wesley Pa", cpf_cnpj: "" },
  { nome: "Joelson Sev", cpf_cnpj: "" },
  { nome: "Anderson A", cpf_cnpj: "" },
  { nome: "Jhonatan R", cpf_cnpj: "" },
  { nome: "Laurencio D", cpf_cnpj: "" },
  { nome: "Mauricio M", cpf_cnpj: "" },
  { nome: "Gerson da", cpf_cnpj: "" },
  { nome: "André Verb", cpf_cnpj: "" },
  { nome: "Tatiane Re", cpf_cnpj: "" },
  { nome: "Thiago San", cpf_cnpj: "" },
  { nome: "Adilson da", cpf_cnpj: "" },
  { nome: "Rogerio M", cpf_cnpj: "" },
  { nome: "Lucas Olive", cpf_cnpj: "" },
  { nome: "Everson Co", cpf_cnpj: "" },
  { nome: "Debora Ke", cpf_cnpj: "" },
  { nome: "Oseias Fer", cpf_cnpj: "" },
  { nome: "Carmen Ta", cpf_cnpj: "" },
  { nome: "Kevin Fider", cpf_cnpj: "" },
  { nome: "Lucimara Iv", cpf_cnpj: "" },
  { nome: "Mauricio A", cpf_cnpj: "" },
  { nome: "Igor da Silv", cpf_cnpj: "" },
  { nome: "Cheila Gab", cpf_cnpj: "" },
  { nome: "Gilberto Ba", cpf_cnpj: "" },
  { nome: "Joaquin Pe", cpf_cnpj: "" },
  { nome: "Rogerio Ap", cpf_cnpj: "" },
  { nome: "Elmo Jose", cpf_cnpj: "" },
  { nome: "Denis Nune", cpf_cnpj: "" },
  { nome: "Nircelio Fa", cpf_cnpj: "" },
  { nome: "André Sant", cpf_cnpj: "" },
  { nome: "Andre de S", cpf_cnpj: "" },
  { nome: "Marco Ant", cpf_cnpj: "" },
  { nome: "Tiago dos S", cpf_cnpj: "" },
  { nome: "Marcelo Ro", cpf_cnpj: "" },
  { nome: "David Wes", cpf_cnpj: "" },
  { nome: "Danilo Oliv", cpf_cnpj: "" },
  { nome: "Paulo Dani", cpf_cnpj: "" },
  { nome: "Rafael Ferr", cpf_cnpj: "" },
  { nome: "Cleibe Jose", cpf_cnpj: "" },
  { nome: "Ancelmo F", cpf_cnpj: "" },
  { nome: "Weslei da P", cpf_cnpj: "" },
  { nome: "Monica Fa", cpf_cnpj: "" },
  { nome: "Aris Mar", cpf_cnpj: "" },
  { nome: "Felipe Arau", cpf_cnpj: "" },
  { nome: "Matheus O", cpf_cnpj: "" },
  { nome: "Beatriz Car", cpf_cnpj: "" },
  { nome: "Emerson L", cpf_cnpj: "" },
  { nome: "Ricardo Da", cpf_cnpj: "" },
  { nome: "Cosme Feit", cpf_cnpj: "" },
  { nome: "Maria do C", cpf_cnpj: "" },
  { nome: "Flavio de O", cpf_cnpj: "" },
  { nome: "onezino Na", cpf_cnpj: "" },
  { nome: "Dilma Sant", cpf_cnpj: "" },
  { nome: "Robson So", cpf_cnpj: "" },
  { nome: "Joel Quitin", cpf_cnpj: "" },
  { nome: "Rogerio Ra", cpf_cnpj: "" },
  { nome: "Marcelo Ba", cpf_cnpj: "" },
  { nome: "Pedro Xavi", cpf_cnpj: "" },
  { nome: "W Ventilad", cpf_cnpj: "" },
  { nome: "Vitor de So", cpf_cnpj: "" },
  { nome: "Wellington", cpf_cnpj: "" },
  { nome: "Lucielene G", cpf_cnpj: "" },
  { nome: "Reinaldo A", cpf_cnpj: "" },
  { nome: "Alisson Fel", cpf_cnpj: "" },
  { nome: "Cesar Crisp", cpf_cnpj: "" },
  { nome: "Veronica L", cpf_cnpj: "" },
  { nome: "Tiago Souz", cpf_cnpj: "" },
  { nome: "Marcello T", cpf_cnpj: "" },
  { nome: "Rafaela Lim", cpf_cnpj: "" },
  { nome: "Osmar Vian", cpf_cnpj: "" },
  { nome: "Rogerio As", cpf_cnpj: "" },
  { nome: "Celson Eur", cpf_cnpj: "" },
  { nome: "Rock Pedro", cpf_cnpj: "" },
  { nome: "José Deilto", cpf_cnpj: "" },
  { nome: "Jair Lisboa", cpf_cnpj: "" },
  { nome: "Maurilio Le", cpf_cnpj: "" },
  { nome: "Tatiana Cri", cpf_cnpj: "" },
  { nome: "João Rodrig", cpf_cnpj: "" },
  { nome: "Cosmo Thi", cpf_cnpj: "" },
  { nome: "Lucas Alve", cpf_cnpj: "" },
  { nome: "Leila Alves", cpf_cnpj: "" },
  { nome: "Vitor Gabr", cpf_cnpj: "" },
  { nome: "Jenifer de A", cpf_cnpj: "" },
  { nome: "Everton Ol", cpf_cnpj: "" },
  { nome: "Renato Bar", cpf_cnpj: "" },
  { nome: "Luis Matias", cpf_cnpj: "" },
  { nome: "Humberto", cpf_cnpj: "" },
  { nome: "Sandro Ne", cpf_cnpj: "" },
  { nome: "Leandro Fr", cpf_cnpj: "" },
  { nome: "Renato Oli", cpf_cnpj: "" },
  { nome: "Luciana do", cpf_cnpj: "" },
  { nome: "Evanildo B", cpf_cnpj: "" },
  { nome: "Alicio Dias", cpf_cnpj: "" },
  { nome: "Junior Luz", cpf_cnpj: "" },
  { nome: "Junior Ceza", cpf_cnpj: "" },
  { nome: "Céu Apare", cpf_cnpj: "" },
  { nome: "Fabio Barb", cpf_cnpj: "" },
  { nome: "Jonathan V", cpf_cnpj: "" },
  { nome: "Isaac da Sil", cpf_cnpj: "" },
  { nome: "Vinicius do", cpf_cnpj: "" },
  { nome: "Edson Mar", cpf_cnpj: "" },
  { nome: "Fabio Mon", cpf_cnpj: "" },
  { nome: "Jose Moise", cpf_cnpj: "" },
  { nome: "Edimilson d", cpf_cnpj: "" },
  { nome: "Rosa Maria", cpf_cnpj: "" },
  { nome: "Wesley de", cpf_cnpj: "" },
  { nome: "Gilvan Can", cpf_cnpj: "" },
  { nome: "Marcelo de", cpf_cnpj: "" },
  { nome: "Joelson Far", cpf_cnpj: "" },
  { nome: "Aécio Dias", cpf_cnpj: "" },
  { nome: "Geraldo", cpf_cnpj: "" },
  { nome: "Eder Santo", cpf_cnpj: "" },
  { nome: "Clayton Jos", cpf_cnpj: "" },
  { nome: "Hugo Garc", cpf_cnpj: "" },
  { nome: "Johnatan M", cpf_cnpj: "" },
  { nome: "Rogerio Lis", cpf_cnpj: "" },
  { nome: "Eneias da S", cpf_cnpj: "" },
  { nome: "Adriano Ja", cpf_cnpj: "" },
  { nome: "Benedito A", cpf_cnpj: "" },
  { nome: "Tiago Henr", cpf_cnpj: "" },
  { nome: "Manoel Ma", cpf_cnpj: "" },
  { nome: "Claudinei R", cpf_cnpj: "" },
  { nome: "Alberto Oli", cpf_cnpj: "" },
  { nome: "Wilton Bat", cpf_cnpj: "" },
  { nome: "Eder da Cru", cpf_cnpj: "" },
  { nome: "Adão Ferre", cpf_cnpj: "" },
  { nome: "Gislene Oli", cpf_cnpj: "" },
  { nome: "Victor Man", cpf_cnpj: "" },
  { nome: "Luis Jardim", cpf_cnpj: "" },
  { nome: "Manuel Pa", cpf_cnpj: "" },
  { nome: "Cassio Gon", cpf_cnpj: "" },
  { nome: "Dimas Jose", cpf_cnpj: "" },
  { nome: "Joelson Fra", cpf_cnpj: "" },
  { nome: "Felipe Nun", cpf_cnpj: "" },
  { nome: "Joviano Ca", cpf_cnpj: "" },
  { nome: "Vanessa He", cpf_cnpj: "" },
  { nome: "Marcelo N", cpf_cnpj: "" },
  { nome: "Paulo Roge", cpf_cnpj: "" },
  { nome: "Karina Mar", cpf_cnpj: "" },
  { nome: "Rodolfo Ca", cpf_cnpj: "" },
  { nome: "Adriana Sil", cpf_cnpj: "" },
  { nome: "Marcos Fe", cpf_cnpj: "" },
  { nome: "Esmael Bar", cpf_cnpj: "" },
  { nome: "Jonathan d", cpf_cnpj: "" },
  { nome: "Patricia Ro", cpf_cnpj: "" },
  { nome: "Vandeir xa", cpf_cnpj: "" },
  { nome: "Tiago Felip", cpf_cnpj: "" },
  { nome: "Edio da Silv", cpf_cnpj: "" },
  { nome: "Carlos hen", cpf_cnpj: "" },
  { nome: "José Nailto", cpf_cnpj: "" },
  { nome: "Gerbesson", cpf_cnpj: "" },
  { nome: "João Adão", cpf_cnpj: "" },
  { nome: "Alessandra", cpf_cnpj: "" },
  { nome: "Cristhian M", cpf_cnpj: "" },
  { nome: "Bruno Vito", cpf_cnpj: "" },
  { nome: "Airton Vito", cpf_cnpj: "" },
  { nome: "Paulo Serg", cpf_cnpj: "" },
  { nome: "Josuel de J", cpf_cnpj: "" },
  { nome: "Ezequel Fe", cpf_cnpj: "" },
  { nome: "Wesley Ap", cpf_cnpj: "" },
  { nome: "Manoel Ro", cpf_cnpj: "" },
  { nome: "Andréa rod", cpf_cnpj: "" },
  { nome: "Quiteria M", cpf_cnpj: "" },
  { nome: "Igor Mesqu", cpf_cnpj: "" },
  { nome: "Rubiane Ke", cpf_cnpj: "" },
  { nome: "Marcio Ros", cpf_cnpj: "" },
  { nome: "Bruno dos", cpf_cnpj: "" },
  { nome: "Valdinei Ro", cpf_cnpj: "" },
  { nome: "Ana Maria", cpf_cnpj: "" },
  { nome: "Alessandro", cpf_cnpj: "" },
  { nome: "Leonardo V", cpf_cnpj: "" },
  { nome: "Rodrigo Ro", cpf_cnpj: "" },
  { nome: "Adriano Fr", cpf_cnpj: "" },
  { nome: "Junior Ferr", cpf_cnpj: "" },
  { nome: "Osaias Dias", cpf_cnpj: "" },
  { nome: "Antonio pe", cpf_cnpj: "" },
  { nome: "Alan Domi", cpf_cnpj: "" },
  { nome: "Jaqueline R", cpf_cnpj: "" },
  { nome: "Gilmar Ma", cpf_cnpj: "" },
  { nome: "Veronica M", cpf_cnpj: "" },
  { nome: "Gilberto Ro", cpf_cnpj: "" },
  { nome: "Daniel Men", cpf_cnpj: "" },
  { nome: "Fabio Silva", cpf_cnpj: "" },
  { nome: "Cleiton Eds", cpf_cnpj: "" },
  { nome: "Talis Ramo", cpf_cnpj: "" },
  { nome: "Eduardo Jo", cpf_cnpj: "" },
  { nome: "Edson Pere", cpf_cnpj: "" },
  { nome: "Henrique L", cpf_cnpj: "" },
  { nome: "Carlos Rob", cpf_cnpj: "" },
  { nome: "Palmira do", cpf_cnpj: "" },
  { nome: "Wagner de", cpf_cnpj: "" },
  { nome: "Bruno Mar", cpf_cnpj: "" },
  { nome: "Ricardo Ba", cpf_cnpj: "" },
  { nome: "Euvan Carv", cpf_cnpj: "" },
  { nome: "Renato Soa", cpf_cnpj: "" },
  { nome: "Igor Santan", cpf_cnpj: "" },
  { nome: "Andre Faus", cpf_cnpj: "" },
  { nome: "Paulo Tiago", cpf_cnpj: "" },
  { nome: "Zilda Rodri", cpf_cnpj: "" },
  { nome: "Tainã Taise", cpf_cnpj: "" },
  { nome: "Gabriel Gri", cpf_cnpj: "" },
  { nome: "Sirinel Paix", cpf_cnpj: "" },
  { nome: "Ulisses Rob", cpf_cnpj: "" },
  { nome: "Cicero Man", cpf_cnpj: "" },
  { nome: "Junio Nata", cpf_cnpj: "" },
  { nome: "David dos S", cpf_cnpj: "" },
  { nome: "Yan Eugen", cpf_cnpj: "" },
  { nome: "Fernando J", cpf_cnpj: "" },
  { nome: "thiago Ribe", cpf_cnpj: "" },
  { nome: "Marcos Na", cpf_cnpj: "" },
  { nome: "Nilton Men", cpf_cnpj: "" },
  { nome: "Luizia Fortu", cpf_cnpj: "" },
  { nome: "Richard Ad", cpf_cnpj: "" },
  { nome: "Rafael Pale", cpf_cnpj: "" },
  { nome: "Valtair Sou", cpf_cnpj: "" },
  { nome: "Marcos Ro", cpf_cnpj: "" },
  { nome: "Bruno Josia", cpf_cnpj: "" },
  { nome: "Amilton de", cpf_cnpj: "" },
  { nome: "Gilmar Pra", cpf_cnpj: "" },
  { nome: "Moacir Lop", cpf_cnpj: "" },
  { nome: "Jose Beijam", cpf_cnpj: "" },
  { nome: "Wilian de S", cpf_cnpj: "" },
  { nome: "Anderson R", cpf_cnpj: "" },
  { nome: "Elvis Carmo", cpf_cnpj: "" },
  { nome: "Claudio Fra", cpf_cnpj: "" },
  { nome: "Jairo Varist", cpf_cnpj: "" },
  { nome: "Fabriana N", cpf_cnpj: "" },
  { nome: "Jose Raimu", cpf_cnpj: "" },
  { nome: "Vicente de", cpf_cnpj: "" },
  { nome: "Carlos Caiq", cpf_cnpj: "" },
  { nome: "Gerson Dia", cpf_cnpj: "" },
  { nome: "Murilo Nas", cpf_cnpj: "" },
  { nome: "Katia Xavie", cpf_cnpj: "" },
  { nome: "David Pere", cpf_cnpj: "" },
  { nome: "Lismar Rod", cpf_cnpj: "" },
  { nome: "Robson Fe", cpf_cnpj: "" },
  { nome: "Juliana Bar", cpf_cnpj: "" },
  { nome: "Izaquel Can", cpf_cnpj: "" },
  { nome: "Robson da", cpf_cnpj: "" },
  { nome: "wellilingto", cpf_cnpj: "" },
  { nome: "Gustavo Ba", cpf_cnpj: "" },
  { nome: "Pablo VInic", cpf_cnpj: "" },
  { nome: "Cleiton Apa", cpf_cnpj: "" },
  { nome: "Augustinho", cpf_cnpj: "" },
  { nome: "Manoel Fe", cpf_cnpj: "" },
  { nome: "Aricide Ram", cpf_cnpj: "" },
  { nome: "Angela Ma", cpf_cnpj: "" },
  { nome: "Jilvanete C", cpf_cnpj: "" },
  { nome: "Kaio More", cpf_cnpj: "" },
  { nome: "Fabiano Je", cpf_cnpj: "" },
  { nome: "Nicolau Sm", cpf_cnpj: "" },
  { nome: "Henrique K", cpf_cnpj: "" },
  { nome: "Irenildo Via", cpf_cnpj: "" },
  { nome: "Jose Ricard", cpf_cnpj: "" },
  { nome: "Fabio Pierr", cpf_cnpj: "" },
  { nome: "Renato Ma", cpf_cnpj: "" },
  { nome: "Jonatas Silv", cpf_cnpj: "" },
  { nome: "Jose Na", cpf_cnpj: "" },
  { nome: "Mauricio F", cpf_cnpj: "" },
  { nome: "Jeremias B", cpf_cnpj: "" },
  { nome: "Renato Car", cpf_cnpj: "" },
  { nome: "Lucas Sant", cpf_cnpj: "" },
  { nome: "Alaelson O", cpf_cnpj: "" },
  { nome: "Renato San", cpf_cnpj: "" },
  { nome: "Cristiano S", cpf_cnpj: "" },
  { nome: "Luis Rodrig", cpf_cnpj: "" },
  { nome: "Marcelo Ri", cpf_cnpj: "" },
  { nome: "Gervacio", cpf_cnpj: "" },
  { nome: "Luiz Austin", cpf_cnpj: "" },
  { nome: "Eidmar Ma", cpf_cnpj: "" },
  { nome: "Samuel Go", cpf_cnpj: "" },
  { nome: "Katia Ferre", cpf_cnpj: "" },
  { nome: "Renato Lim", cpf_cnpj: "" },
  { nome: "Caique Pim", cpf_cnpj: "" },
  { nome: "Paulo Espie", cpf_cnpj: "" },
  { nome: "Joao Carlos", cpf_cnpj: "" },
  { nome: "Marco Ant", cpf_cnpj: "" },
  { nome: "Leandro Al", cpf_cnpj: "" },
  { nome: "Kaua Paulo", cpf_cnpj: "" },
  { nome: "Nesto Mor", cpf_cnpj: "" },
  { nome: "Ana Paula", cpf_cnpj: "" },
  { nome: "Eduardo So", cpf_cnpj: "" },
  { nome: "Alecxande", cpf_cnpj: "" },
  { nome: "Cristiana A", cpf_cnpj: "" },
  { nome: "Jose Gome", cpf_cnpj: "" },
  { nome: "Edilson Am", cpf_cnpj: "" },
  { nome: "Jose Cicero", cpf_cnpj: "" },
  { nome: "Valdemar L", cpf_cnpj: "" },
  { nome: "Joao Victor", cpf_cnpj: "" },
  { nome: "Elias Mend", cpf_cnpj: "" },
  { nome: "Ailson And", cpf_cnpj: "" },
  { nome: "Edivan Fre", cpf_cnpj: "" },
  { nome: "Gadeon Go", cpf_cnpj: "" },
  { nome: "Edilma Ma", cpf_cnpj: "" },
  { nome: "Marcio Cle", cpf_cnpj: "" },
  { nome: "Ronie Dias", cpf_cnpj: "" },
  { nome: "Matheus", cpf_cnpj: "" },
  { nome: "Marcos Fre", cpf_cnpj: "" },
  { nome: "Gabriel de", cpf_cnpj: "" },
  { nome: "Bruna da S", cpf_cnpj: "" },
  { nome: "Paulo Vitor", cpf_cnpj: "" },
  { nome: "Fernando N", cpf_cnpj: "" },
  { nome: "Sergio Rob", cpf_cnpj: "" },
  { nome: "Joilton Que", cpf_cnpj: "" },
  { nome: "Diogo Carv", cpf_cnpj: "" },
  { nome: "Waldir Me", cpf_cnpj: "" },
  { nome: "Robson Afo", cpf_cnpj: "" },
  { nome: "Paulo De T", cpf_cnpj: "" },
  { nome: "Vinicius Mo", cpf_cnpj: "" },
  { nome: "Isabela Fer", cpf_cnpj: "" },
  { nome: "Alan dos Sa", cpf_cnpj: "" },
  { nome: "Cesar de Je", cpf_cnpj: "" },
  { nome: "Miriam Fag", cpf_cnpj: "" },
  { nome: "Roberto Pe", cpf_cnpj: "" },
  { nome: "Valdir Caet", cpf_cnpj: "" },
  { nome: "Caio Sergio", cpf_cnpj: "" },
  { nome: "Domingos", cpf_cnpj: "" },
  { nome: "Moises An", cpf_cnpj: "" },
  { nome: "Marcio Per", cpf_cnpj: "" },
  { nome: "Benedito L", cpf_cnpj: "" },
  { nome: "Jhon Erick", cpf_cnpj: "" },
  { nome: "Eleno Sant", cpf_cnpj: "" },
  { nome: "Lucas Jesse", cpf_cnpj: "" },
  { nome: "Rian Santo", cpf_cnpj: "" },
  { nome: "Daniel Vile", cpf_cnpj: "" },
  { nome: "Debora de", cpf_cnpj: "" },
  { nome: "Aldenisio Z", cpf_cnpj: "" },
  { nome: "Isaias Silva", cpf_cnpj: "" },
  { nome: "montagem", cpf_cnpj: "" },
  { nome: "Edvaldo Ri", cpf_cnpj: "" },
  { nome: "Isis Pereira", cpf_cnpj: "" },
  { nome: "Edemilson", cpf_cnpj: "" },
  { nome: "Wagner Go", cpf_cnpj: "" },
  { nome: "Felipe Mat", cpf_cnpj: "" },
  { nome: "Anderson S", cpf_cnpj: "" },
  { nome: "Jorge Luiz H", cpf_cnpj: "" },
  { nome: "Jorge Luiz R", cpf_cnpj: "" },
  { nome: "Rogerio Ne", cpf_cnpj: "" },
  { nome: "Sabrina Na", cpf_cnpj: "" },
  { nome: "Fabio Estev", cpf_cnpj: "" },
  { nome: "Guilherme", cpf_cnpj: "" },
  { nome: "Thaina Sou", cpf_cnpj: "" },
  { nome: "Henrique N", cpf_cnpj: "" },
  { nome: "Thiago Fer", cpf_cnpj: "" },
  { nome: "Sara Figuei", cpf_cnpj: "" },
  { nome: "Eliseu Figu", cpf_cnpj: "" },
  { nome: "Joao Pedro", cpf_cnpj: "" },
  { nome: "Reinaldo M", cpf_cnpj: "" },
  { nome: "Robert Rich", cpf_cnpj: "" },
  { nome: "Lucas Batis", cpf_cnpj: "" },
  { nome: "Franklin W", cpf_cnpj: "" },
  { nome: "Flavio Fern", cpf_cnpj: "" },
  { nome: "Cleber Mot", cpf_cnpj: "" },
  { nome: "Sandro de", cpf_cnpj: "" },
  { nome: "Rafael da C", cpf_cnpj: "" },
  { nome: "Enias Faust", cpf_cnpj: "" },
  { nome: "Sheila Crist", cpf_cnpj: "" },
  { nome: "Ricardo Fra", cpf_cnpj: "" },
  { nome: "Vania Sant", cpf_cnpj: "" },
  { nome: "Marcelo Pa", cpf_cnpj: "" },
  { nome: "Felipe de S", cpf_cnpj: "" },
  { nome: "Renato roc", cpf_cnpj: "" },
  { nome: "Genivaldo", cpf_cnpj: "" },
  { nome: "Alan alves", cpf_cnpj: "" },
  { nome: "Ygor Alex", cpf_cnpj: "" },
  { nome: "Vitor Hugo", cpf_cnpj: "" },
  { nome: "Murilo Hen", cpf_cnpj: "" },
  { nome: "Valdir Viera", cpf_cnpj: "" },
  { nome: "Carlos Hen", cpf_cnpj: "" },
  { nome: "Edivan Cas", cpf_cnpj: "" },
  { nome: "Michael Ra", cpf_cnpj: "" },
  { nome: "Miguel Fra", cpf_cnpj: "" },
  { nome: "Geraldo Re", cpf_cnpj: "" },
  { nome: "Wildes Alv", cpf_cnpj: "" },
  { nome: "Ismael Xav", cpf_cnpj: "" },
  { nome: "Jonatan Ro", cpf_cnpj: "" },
  { nome: "Cicero Alfr", cpf_cnpj: "" },
  { nome: "Elizeu Tom", cpf_cnpj: "" },
  { nome: "Jose Ailton", cpf_cnpj: "" },
  { nome: "Leomar Ca", cpf_cnpj: "" },
  { nome: "Josiaria San", cpf_cnpj: "" },
  { nome: "Edson Luz", cpf_cnpj: "" },
  { nome: "Geovane M", cpf_cnpj: "" },
  { nome: "Richard do", cpf_cnpj: "" },
  { nome: "Gil Fernand", cpf_cnpj: "" },
  { nome: "Fabio Jose", cpf_cnpj: "" },
  { nome: "Rogerio Alm", cpf_cnpj: "" },
  { nome: "Enderson M", cpf_cnpj: "" },
  { nome: "silas santos", cpf_cnpj: "" },
  { nome: "tiago alves", cpf_cnpj: "" },
  { nome: "Diogo Benv", cpf_cnpj: "" },
  { nome: "Cleberson", cpf_cnpj: "" },
  { nome: "Joselio Can", cpf_cnpj: "" },
  { nome: "Junior Milt", cpf_cnpj: "" },
  { nome: "Helio Nogu", cpf_cnpj: "" },
  { nome: "Caroline Na", cpf_cnpj: "" },
  { nome: "Onildo Ribe", cpf_cnpj: "" },
  { nome: "Amauri Ma", cpf_cnpj: "" },
  { nome: "Elton Silva", cpf_cnpj: "" },
  { nome: "Manoel Jos", cpf_cnpj: "" },
  { nome: "Angelica N", cpf_cnpj: "" },
  { nome: "Caetano Si", cpf_cnpj: "" },
  { nome: "Rafael men", cpf_cnpj: "" },
  { nome: "Michel Oliv", cpf_cnpj: "" },
  { nome: "Jose Ildo B", cpf_cnpj: "" },
  { nome: "Antonio Ar", cpf_cnpj: "" },
  { nome: "Fernanda d", cpf_cnpj: "" },
  { nome: "roberto via", cpf_cnpj: "" },
  { nome: "Gustavo M", cpf_cnpj: "" },
  { nome: "Wagner Cla", cpf_cnpj: "" },
  { nome: "Edemar Ga", cpf_cnpj: "" },
  { nome: "Marcos Jos", cpf_cnpj: "" },
  { nome: "Ingrid de p", cpf_cnpj: "" },
  { nome: "Joao Vitor", cpf_cnpj: "" },
  { nome: "Marcos Aq", cpf_cnpj: "" },
  { nome: "Silvio Simo", cpf_cnpj: "" },
  { nome: "Renner da", cpf_cnpj: "" },
  { nome: "Fabiana Te", cpf_cnpj: "" },
  { nome: "Ranyeri Ch", cpf_cnpj: "" },
  { nome: "Thiago Rod", cpf_cnpj: "" },
  { nome: "Renan Feli", cpf_cnpj: "" },
  { nome: "Bruna Arau", cpf_cnpj: "" },
  { nome: "Rafael Sou", cpf_cnpj: "" },
  { nome: "Rubens Pa", cpf_cnpj: "" },
  { nome: "Valter Carl", cpf_cnpj: "" },
  { nome: "Jeferson da", cpf_cnpj: "" },
  { nome: "Tiago Do N", cpf_cnpj: "" },
  { nome: "Éric Cleyto", cpf_cnpj: "" },
  { nome: "Antônio Ro", cpf_cnpj: "" },
  { nome: "Marinavo D", cpf_cnpj: "" },
  { nome: "Luiz Florên", cpf_cnpj: "" },
  { nome: "Claudiney J", cpf_cnpj: "" },
  { nome: "Jonatas Dia", cpf_cnpj: "" },
  { nome: "Diego Bern", cpf_cnpj: "" },
  { nome: "Admir Gon", cpf_cnpj: "" },
  { nome: "Edgar salom", cpf_cnpj: "" },
  { nome: "Francisco T", cpf_cnpj: "" },
  { nome: "Fabricio Fe", cpf_cnpj: "" },
  { nome: "Fabio Bona", cpf_cnpj: "" },
  { nome: "Hugo faria", cpf_cnpj: "" },
  { nome: "Lealdo Silv", cpf_cnpj: "" },
  { nome: "Jonas Alve", cpf_cnpj: "" },
  { nome: "Weliton Sa", cpf_cnpj: "" },
  { nome: "Débora Rib", cpf_cnpj: "" },
  { nome: "Everaldo F", cpf_cnpj: "" },
  { nome: "Evanildo Sa", cpf_cnpj: "" },
  { nome: "Eleno Luís", cpf_cnpj: "" },
  { nome: "Ernesto Lib", cpf_cnpj: "" },
  { nome: "Denis Milto", cpf_cnpj: "" },
  { nome: "Cleiton Lisb", cpf_cnpj: "" },
  { nome: "Jefferson", cpf_cnpj: "" },
  { nome: "Charle Ara", cpf_cnpj: "" },
  { nome: "Luan Vieira", cpf_cnpj: "" },
  { nome: "Cleiton Oliv", cpf_cnpj: "" },
  { nome: "Suzana Brit", cpf_cnpj: "" },
  { nome: "Gustavo Ro", cpf_cnpj: "" },
  { nome: "Emersom B", cpf_cnpj: "" },
  { nome: "Bruna Batis", cpf_cnpj: "" },
  { nome: "Airon Gom", cpf_cnpj: "" },
  { nome: "Otavio Wa", cpf_cnpj: "" },
  { nome: "Marivaldo", cpf_cnpj: "" },
  { nome: "Jose Carlos", cpf_cnpj: "" },
  { nome: "Cleuson Te", cpf_cnpj: "" },
  { nome: "Márcio Per", cpf_cnpj: "" },
  { nome: "Jerônimo M", cpf_cnpj: "" },
  { nome: "Fabiano Pe", cpf_cnpj: "" },
  { nome: "Pedro Hen", cpf_cnpj: "" },
  { nome: "Johan Cris", cpf_cnpj: "" },
  { nome: "Cisaro Ema", cpf_cnpj: "" },
  { nome: "Pedro Cava", cpf_cnpj: "" },
  { nome: "Hermes Su", cpf_cnpj: "" },
  { nome: "Eduardo Va", cpf_cnpj: "" },
  { nome: "Armando J", cpf_cnpj: "" },
  { nome: "Marinele L", cpf_cnpj: "" },
  { nome: "Ronaldo Pe", cpf_cnpj: "" },
  { nome: "Erick Robe", cpf_cnpj: "" },
  { nome: "Caike Men", cpf_cnpj: "" },
  { nome: "Lauro Antô", cpf_cnpj: "" },
  { nome: "Willian Alb", cpf_cnpj: "" },
  { nome: "José Rober", cpf_cnpj: "" },
  { nome: "Luis Carlos", cpf_cnpj: "" },
  { nome: "Black gelo", cpf_cnpj: "" },
  { nome: "Agilson San", cpf_cnpj: "" },
  { nome: "Rafael Silva", cpf_cnpj: "" },
  { nome: "Sergio da S", cpf_cnpj: "" },
  { nome: "Alecsandre", cpf_cnpj: "" },
  { nome: "José Antôn", cpf_cnpj: "" },
  { nome: "Evandro do", cpf_cnpj: "" },
  { nome: "Bruno Ema", cpf_cnpj: "" },
  { nome: "Danilo torr", cpf_cnpj: "" },
  { nome: "Edemilson", cpf_cnpj: "" },
  { nome: "Cilio Cesa", cpf_cnpj: "" },
  { nome: "Marcos Isr", cpf_cnpj: "" },
  { nome: "Anderson P", cpf_cnpj: "" },
  { nome: "Wilson de", cpf_cnpj: "" },
  { nome: "Flavio Olive", cpf_cnpj: "" },
  { nome: "Joelmo Pei", cpf_cnpj: "" },
  { nome: "Jorlei Ribei", cpf_cnpj: "" },
  { nome: "Glaucio da", cpf_cnpj: "" },
  { nome: "Simião Rib", cpf_cnpj: "" },
  { nome: "Laercio Rod", cpf_cnpj: "" },
  { nome: "Natalicio Jo", cpf_cnpj: "" },
  { nome: "Valter Ram", cpf_cnpj: "" },
  { nome: "Eduardo M", cpf_cnpj: "" },
  { nome: "Jackson So", cpf_cnpj: "" },
  { nome: "Emanuel Ja", cpf_cnpj: "" },
  { nome: "Joelson Ba", cpf_cnpj: "" },
  { nome: "Mizael Alb", cpf_cnpj: "" },
  { nome: "Rodrigo Ab", cpf_cnpj: "" },
  { nome: "chico viana", cpf_cnpj: "" },
  { nome: "Kleiton Sim", cpf_cnpj: "" },
  { nome: "Erivaldo Ol", cpf_cnpj: "" },
  { nome: "Jose evang", cpf_cnpj: "" },
  { nome: "Leonardo A", cpf_cnpj: "" },
  { nome: "Vicente Rib", cpf_cnpj: "" },
  { nome: "Diego Sant", cpf_cnpj: "" },
  { nome: "Maria Crist", cpf_cnpj: "" },
  { nome: "Maurício Jo", cpf_cnpj: "" },
  { nome: "Maycran F", cpf_cnpj: "" },
  { nome: "Sandro Fre", cpf_cnpj: "" },
  { nome: "Francisco", cpf_cnpj: "" },
  { nome: "Vitor Mart", cpf_cnpj: "" },
  { nome: "Gustavo Fr", cpf_cnpj: "" },
  { nome: "djamal ferr", cpf_cnpj: "" },
  { nome: "Eduardo Vi", cpf_cnpj: "" },
  { nome: "Hebert Ric", cpf_cnpj: "" },
  { nome: "Angelo Ma", cpf_cnpj: "" },
  { nome: "Alexandre", cpf_cnpj: "" },
  { nome: "José Cristó", cpf_cnpj: "" },
  { nome: "VanClebers", cpf_cnpj: "" },
  { nome: "Felipe Lima", cpf_cnpj: "" },
  { nome: "Wederson", cpf_cnpj: "" },
  { nome: "Fabio xavie", cpf_cnpj: "" },
  { nome: "Vanessa de", cpf_cnpj: "" },
  { nome: "Jhonathan", cpf_cnpj: "" },
  { nome: "Valmir Inác", cpf_cnpj: "" },
  { nome: "Jamille Oliv", cpf_cnpj: "" },
  { nome: "Vitor vinici", cpf_cnpj: "" },
  { nome: "Luciano ca", cpf_cnpj: "" },
  { nome: "Fernando S", cpf_cnpj: "" },
  { nome: "Nelson dom", cpf_cnpj: "" },
  { nome: "Donizete A", cpf_cnpj: "" },
  { nome: "Leandro Ch", cpf_cnpj: "" },
  { nome: "Edneia Ram", cpf_cnpj: "" },
  { nome: "Vagner Fer", cpf_cnpj: "" },
  { nome: "Lenildo San", cpf_cnpj: "" },
  { nome: "José Danta", cpf_cnpj: "" },
  { nome: "Bruno Silva", cpf_cnpj: "" },
  { nome: "Welinton d", cpf_cnpj: "" },
  { nome: "José de Alm", cpf_cnpj: "" },
  { nome: "Alex Santo", cpf_cnpj: "" },
  { nome: "Francisco d", cpf_cnpj: "" },
  { nome: "Édison Viei", cpf_cnpj: "" },
  { nome: "Givanildo", cpf_cnpj: "" },
  { nome: "Marsílio Jr", cpf_cnpj: "" },
  { nome: "Philip lima", cpf_cnpj: "" },
  { nome: "Marcos pa", cpf_cnpj: "" },
  { nome: "Marcos Vin", cpf_cnpj: "" },
  { nome: "William ter", cpf_cnpj: "" },
  { nome: "Felipe Alve", cpf_cnpj: "" },
  { nome: "Gustavo H", cpf_cnpj: "" },
  { nome: "Maria cicer", cpf_cnpj: "" },
  { nome: "Jadson per", cpf_cnpj: "" },
  { nome: "Josuel Ram", cpf_cnpj: "" },
  { nome: "Danilo dor", cpf_cnpj: "" },
  { nome: "Andre alve", cpf_cnpj: "" },
  { nome: "Vagner ribe", cpf_cnpj: "" },
  { nome: "Gustavo m", cpf_cnpj: "" },
  { nome: "Tassio da s", cpf_cnpj: "" },
  { nome: "Ricardo So", cpf_cnpj: "" },
  { nome: "Edson Sant", cpf_cnpj: "" },
  { nome: "Valdemir L", cpf_cnpj: "" },
  { nome: "Wander As", cpf_cnpj: "" },
  { nome: "Rogerio W", cpf_cnpj: "" },
  { nome: "Benedito", cpf_cnpj: "" },
  { nome: "Jose Petro", cpf_cnpj: "" },
  { nome: "Ricardo He", cpf_cnpj: "" },
  { nome: "Adilson Do", cpf_cnpj: "" },
  { nome: "Marcos de", cpf_cnpj: "" },
  { nome: "Vitor Viníci", cpf_cnpj: "" },
  { nome: "Rodrigo do", cpf_cnpj: "" },
  { nome: "Edeson Go", cpf_cnpj: "" },
  { nome: "Dennis Fer", cpf_cnpj: "" },
  { nome: "Miguelito", cpf_cnpj: "" },
  { nome: "Vagner Ma", cpf_cnpj: "" },
  { nome: "Gabriel dos", cpf_cnpj: "" },
  { nome: "Gilberto Re", cpf_cnpj: "" },
  { nome: "Ralf Pereira", cpf_cnpj: "" },
  { nome: "Ronildo Dia", cpf_cnpj: "" },
  { nome: "Renato Pol", cpf_cnpj: "" },
  { nome: "Roberto Da", cpf_cnpj: "" },
  { nome: "Weverton", cpf_cnpj: "" },
  { nome: "Leandro Ro", cpf_cnpj: "" },
  { nome: "Hermes Sil", cpf_cnpj: "" },
  { nome: "Gabriel Sou", cpf_cnpj: "" },
  { nome: "Milton do s", cpf_cnpj: "" },
  { nome: "Edineia Ra", cpf_cnpj: "" },
  { nome: "Adalberto", cpf_cnpj: "" },
  { nome: "Fernando C", cpf_cnpj: "" },
  { nome: "Edivaldo G", cpf_cnpj: "" },
  { nome: "Matheus S", cpf_cnpj: "" },
  { nome: "Milton Cez", cpf_cnpj: "" },
  { nome: "Cícero Alfr", cpf_cnpj: "" },
  { nome: "Raimundo", cpf_cnpj: "" },
  { nome: "Aloísio dos", cpf_cnpj: "" },
  { nome: "Murilo Pen", cpf_cnpj: "" },
  { nome: "Ruan Felip", cpf_cnpj: "" },
  { nome: "Marcus ma", cpf_cnpj: "" },
  { nome: "Alipio Alve", cpf_cnpj: "" },
  { nome: "Francisco G", cpf_cnpj: "" },
  { nome: "Jailton Ferr", cpf_cnpj: "" },
  { nome: "Luís Carlos", cpf_cnpj: "" },
  { nome: "Lucas de M", cpf_cnpj: "" },
  { nome: "Joselho Bo", cpf_cnpj: "" },
  { nome: "Josué Pedr", cpf_cnpj: "" },
  { nome: "Rogério Ra", cpf_cnpj: "" },
  { nome: "Adriano Via", cpf_cnpj: "" },
  { nome: "Jailton Gom", cpf_cnpj: "" },
  { nome: "Gleice font", cpf_cnpj: "" },
  { nome: "Fabio da Co", cpf_cnpj: "" },
  { nome: "Thales Oliv", cpf_cnpj: "" },
  { nome: "Cesar de ca", cpf_cnpj: "" },
  { nome: "José Cláud", cpf_cnpj: "" },
  { nome: "Gilberto Sa", cpf_cnpj: "" },
  { nome: "Bruno Ram", cpf_cnpj: "" },
  { nome: "Samuel Fer", cpf_cnpj: "" },
  { nome: "Rogério Ra", cpf_cnpj: "" },
  { nome: "Marcos An", cpf_cnpj: "" },
];

// Lojas
const lojas = [{ nome: "Loja Matriz", cidade: "Suzano", estado: "SP" }];

// Colaborador padrão (vendedor)
const colaboradores = [
  { nome: "Isabela", funcao: "Vendedora", ativo: true }
];

// Vendas extraídas do PDF (primeiras ~200 vendas como exemplo)
const vendas = [
  { codigo: "7", cliente: "Julio Cesar", valor: 359.80, lucro: 159.80 },
  { codigo: "8", cliente: "Thamires R", valor: 399.80, lucro: 199.80 },
  { codigo: "9", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "11", cliente: "consumido", valor: 100.00, lucro: 50.00 },
  { codigo: "12", cliente: "Edivau Ber", valor: 399.80, lucro: 199.80 },
  { codigo: "16", cliente: "Marcio Gle", valor: 409.80, lucro: 209.80 },
  { codigo: "17", cliente: "Ederson Ol", valor: 399.80, lucro: 199.80 },
  { codigo: "18", cliente: "consumido", valor: 50.00, lucro: 0 },
  { codigo: "19", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "20", cliente: "Jorge Luis", valor: 429.80, lucro: 229.80 },
  { codigo: "21", cliente: "Gilberto M", valor: 409.80, lucro: 209.80 },
  { codigo: "22", cliente: "José Luís G", valor: 359.80, lucro: 159.80 },
  { codigo: "23", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "24", cliente: "consumido", valor: 80.00, lucro: 30.00 },
  { codigo: "25", cliente: "Paulo Cesa", valor: 199.90, lucro: 99.90 },
  { codigo: "26", cliente: "Armando B", valor: 189.90, lucro: 89.90 },
  { codigo: "27", cliente: "consumido", valor: 50.00, lucro: 0 },
  { codigo: "28", cliente: "consumido", valor: 200.00, lucro: 100.00 },
  { codigo: "29", cliente: "Rosildo zal", valor: 189.90, lucro: 89.90 },
  { codigo: "30", cliente: "Alexandre", valor: 629.70, lucro: 329.70 },
  { codigo: "31", cliente: "Gesuele Fa", valor: 379.80, lucro: 179.80 },
  { codigo: "32", cliente: "Aparecido", valor: 359.80, lucro: 159.80 },
  { codigo: "33", cliente: "Antônio Pe", valor: 679.60, lucro: 279.60 },
  { codigo: "34", cliente: "Israel Leite", valor: 239.90, lucro: 139.90 },
  { codigo: "35", cliente: "Luiz Serafim", valor: 199.90, lucro: 99.90 },
  { codigo: "36", cliente: "Israel Leite", valor: 40.00, lucro: 40.00 },
  { codigo: "37", cliente: "Marcio Ma", valor: 1080.00, lucro: 680.00 },
  { codigo: "38", cliente: "consumido", valor: 359.80, lucro: 159.80 },
  { codigo: "39", cliente: "Bruno da S", valor: 199.90, lucro: 99.90 },
  { codigo: "40", cliente: "Ronaldo Fe", valor: 379.80, lucro: 179.80 },
  { codigo: "41", cliente: "Bartolome", valor: 439.80, lucro: 239.80 },
  { codigo: "42", cliente: "Sergio Felix", valor: 30.00, lucro: 30.00 },
  { codigo: "43", cliente: "Adriana do", valor: 399.80, lucro: 199.80 },
  { codigo: "44", cliente: "Michael Do", valor: 399.80, lucro: 199.80 },
  { codigo: "46", cliente: "consumido", valor: 140.00, lucro: 40.00 },
  { codigo: "47", cliente: "consumido", valor: 70.00, lucro: 20.00 },
  { codigo: "48", cliente: "Valdir Afon", valor: 799.60, lucro: 399.60 },
  { codigo: "49", cliente: "Antonio Ro", valor: 439.80, lucro: 239.80 },
  { codigo: "50", cliente: "consumido", valor: 340.00, lucro: 240.00 },
  { codigo: "51", cliente: "João Batist", valor: 179.90, lucro: 79.90 },
  { codigo: "52", cliente: "Fabio Roch", valor: 199.90, lucro: 99.90 },
  { codigo: "53", cliente: "Jose Salmo", valor: 439.80, lucro: 239.80 },
  { codigo: "54", cliente: "Claudinei d", valor: 479.80, lucro: 279.80 },
  { codigo: "56", cliente: "Cristiano Jo", valor: 160.00, lucro: 60.00 },
  { codigo: "57", cliente: "Paulo Jose", valor: 439.80, lucro: 239.80 },
  { codigo: "58", cliente: "Anderson E", valor: 199.90, lucro: 99.90 },
  { codigo: "59", cliente: "Jose Claud", valor: 399.80, lucro: 199.80 },
  { codigo: "60", cliente: "Luiz Alfred", valor: 439.80, lucro: 239.80 },
  { codigo: "61", cliente: "Gabriele Th", valor: 199.90, lucro: 99.90 },
  { codigo: "63", cliente: "Janaina Me", valor: 399.80, lucro: 199.80 },
  { codigo: "64", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "65", cliente: "Joab Alves", valor: 179.90, lucro: 79.90 },
  { codigo: "66", cliente: "Felipe Muz", valor: 799.60, lucro: 399.60 },
  { codigo: "67", cliente: "Almirindo M", valor: 179.90, lucro: 79.90 },
  { codigo: "68", cliente: "consumido", valor: 20.00, lucro: 20.00 },
  { codigo: "69", cliente: "Jose Elder", valor: 419.80, lucro: 219.80 },
  { codigo: "70", cliente: "Maria Elen", valor: 280.00, lucro: 80.00 },
  { codigo: "71", cliente: "Celio Luis d", valor: 160.00, lucro: 60.00 },
  { codigo: "72", cliente: "Paulo Cesa", valor: 140.00, lucro: 90.00 },
  { codigo: "73", cliente: "Everton Pin", valor: 419.80, lucro: 219.80 },
  { codigo: "74", cliente: "Jenivaldo A", valor: 359.80, lucro: 159.80 },
  { codigo: "75", cliente: "Petrucio Co", valor: 879.60, lucro: 479.60 },
  { codigo: "76", cliente: "Leandro Ni", valor: 70.00, lucro: 20.00 },
  { codigo: "77", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "78", cliente: "consumido", valor: 20.00, lucro: 20.00 },
  { codigo: "79", cliente: "Arlindo Sou", valor: 399.80, lucro: 199.80 },
  { codigo: "80", cliente: "consumido", valor: 50.00, lucro: 50.00 },
  { codigo: "81", cliente: "Jose Soare", valor: 399.80, lucro: 199.80 },
  { codigo: "82", cliente: "Rubens San", valor: 419.80, lucro: 219.80 },
  { codigo: "83", cliente: "Walis da Si", valor: 359.80, lucro: 159.80 },
  { codigo: "85", cliente: "consumido", valor: 100.00, lucro: 50.00 },
  { codigo: "86", cliente: "consumido", valor: 50.00, lucro: 50.00 },
  { codigo: "87", cliente: "consumido", valor: 100.00, lucro: 50.00 },
  { codigo: "88", cliente: "consumido", valor: 200.00, lucro: 100.00 },
  { codigo: "89", cliente: "Francisco L", valor: 799.60, lucro: 399.60 },
  { codigo: "90", cliente: "Stive Cardo", valor: 270.00, lucro: 170.00 },
  { codigo: "92", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "93", cliente: "Marcos Vin", valor: 439.80, lucro: 239.80 },
  { codigo: "94", cliente: "Felipe", valor: 199.90, lucro: 99.90 },
  { codigo: "95", cliente: "Stive Cardo", valor: 270.00, lucro: 170.00 },
  { codigo: "96", cliente: "Andre Luis", valor: 179.90, lucro: 79.90 },
  { codigo: "97", cliente: "Leticia Ada", valor: 719.60, lucro: 319.60 },
  { codigo: "98", cliente: "Claudemir", valor: 359.80, lucro: 159.80 },
  { codigo: "99", cliente: "Everton Go", valor: 379.80, lucro: 179.80 },
  { codigo: "100", cliente: "consumido", valor: 50.00, lucro: 0 },
  { codigo: "101", cliente: "Renan da S", valor: 179.90, lucro: 79.90 },
  { codigo: "102", cliente: "Angelica A", valor: 799.60, lucro: 399.60 },
  { codigo: "103", cliente: "consumido", valor: 100.00, lucro: 50.00 },
  { codigo: "104", cliente: "Cassiano d", valor: 399.80, lucro: 199.80 },
  { codigo: "105", cliente: "Alison Mes", valor: 379.80, lucro: 179.80 },
  { codigo: "106", cliente: "Ronaldo Ar", valor: 629.70, lucro: 329.70 },
  { codigo: "107", cliente: "Cicera Stef", valor: 199.90, lucro: 99.90 },
  { codigo: "108", cliente: "Alex Valeri", valor: 399.80, lucro: 199.80 },
  { codigo: "109", cliente: "Jorge", valor: 179.90, lucro: 79.90 },
  { codigo: "110", cliente: "consumido", valor: 50.00, lucro: 0 },
  { codigo: "111", cliente: "consumido", valor: 80.00, lucro: 30.00 },
  { codigo: "112", cliente: "consumido", valor: 240.00, lucro: 140.00 },
  { codigo: "113", cliente: "consumido", valor: 150.00, lucro: 50.00 },
  { codigo: "114", cliente: "Ronaldo Ar", valor: 339.80, lucro: 239.80 },
  { codigo: "115", cliente: "Bruno Azar", valor: 379.80, lucro: 179.80 },
  { codigo: "116", cliente: "Maisom Ap", valor: 409.80, lucro: 209.80 },
  { codigo: "117", cliente: "Mirley Mes", valor: 540.00, lucro: 340.00 },
  { codigo: "118", cliente: "Edson Reis", valor: 219.90, lucro: 119.90 },
  { codigo: "119", cliente: "consumido", valor: 120.00, lucro: 70.00 },
  { codigo: "120", cliente: "Ezequiel da", valor: 399.80, lucro: 199.80 },
  { codigo: "121", cliente: "Carlos Elde", valor: 540.00, lucro: 340.00 },
  { codigo: "122", cliente: "Camila Alv", valor: 249.80, lucro: 149.80 },
  { codigo: "123", cliente: "Daniel Pere", valor: 399.80, lucro: 199.80 },
  { codigo: "124", cliente: "Gustavo An", valor: 49.90, lucro: 49.90 },
  { codigo: "125", cliente: "Vinicius", valor: 399.80, lucro: 199.80 },
  { codigo: "126", cliente: "Gustavo", valor: 199.90, lucro: 99.90 },
  { codigo: "127", cliente: "Gilberto M", valor: 409.80, lucro: 209.80 },
  { codigo: "128", cliente: "consumido", valor: 50.00, lucro: 50.00 },
  { codigo: "129", cliente: "Claudio Ca", valor: 439.80, lucro: 239.80 },
  { codigo: "130", cliente: "Sirineu Pai", valor: 459.80, lucro: 259.80 },
  { codigo: "131", cliente: "Gilberto Si", valor: 219.90, lucro: 119.90 },
  { codigo: "132", cliente: "Paulo Serg", valor: 99.80, lucro: 99.80 },
  { codigo: "133", cliente: "Gerson de", valor: 419.80, lucro: 219.80 },
  { codigo: "134", cliente: "Roberto Ba", valor: 549.50, lucro: 349.50 },
  { codigo: "135", cliente: "Gilberto Al", valor: 439.80, lucro: 239.80 },
  { codigo: "136", cliente: "consumido", valor: 50.00, lucro: 50.00 },
  { codigo: "137", cliente: "consumido", valor: 30.00, lucro: 30.00 },
  { codigo: "138", cliente: "consumido", valor: 0, lucro: -100 },
  { codigo: "139", cliente: "consumido", valor: 50.00, lucro: 0 },
  { codigo: "140", cliente: "José Luís G", valor: 0, lucro: -100 },
  { codigo: "141", cliente: "Izaias Cost", valor: 189.70, lucro: 189.70 },
  { codigo: "142", cliente: "Caio Evand", valor: 389.60, lucro: 289.60 },
  { codigo: "143", cliente: "Rodrigo Gu", valor: 649.60, lucro: 249.60 },
  { codigo: "144", cliente: "Igor Rodrig", valor: 439.80, lucro: 239.80 },
  { codigo: "145", cliente: "Jose Rober", valor: 779.60, lucro: 379.60 },
  { codigo: "147", cliente: "João Carlos", valor: 360.00, lucro: 260.00 },
  { codigo: "148", cliente: "Paulo Robe", valor: 569.50, lucro: 369.50 },
  { codigo: "149", cliente: "Arnaldo Pio", valor: 399.80, lucro: 199.80 },
  { codigo: "150", cliente: "Rubens Silv", valor: 429.70, lucro: 229.70 },
  { codigo: "151", cliente: "Jose Maria", valor: 549.50, lucro: 349.50 },
  { codigo: "152", cliente: "Mario And", valor: 399.80, lucro: 199.80 },
  { codigo: "153", cliente: "Milton Vila", valor: 399.80, lucro: 199.80 },
  { codigo: "154", cliente: "Jose Loure", valor: 199.90, lucro: 99.90 },
  { codigo: "155", cliente: "consumido", valor: 20.00, lucro: 20.00 },
  { codigo: "156", cliente: "consumido", valor: 100.00, lucro: 50.00 },
  { codigo: "157", cliente: "Jessica Fer", valor: 199.90, lucro: 99.90 },
  { codigo: "158", cliente: "Reginaldo", valor: 399.80, lucro: 199.80 },
  { codigo: "159", cliente: "Adriano da", valor: 399.80, lucro: 199.80 },
  { codigo: "160", cliente: "Beijamim E", valor: 359.80, lucro: 159.80 },
  { codigo: "161", cliente: "consumido", valor: 189.70, lucro: 189.70 },
  { codigo: "162", cliente: "Edson Luis", valor: 399.80, lucro: 199.80 },
];

async function importar() {
  console.log("🚗 BS Oficina Web - Importador de Dados\n");

  // 1. Importar loja
  console.log("📥 Importando loja...");
  const { data: lojaData, error: lojaErr } = await supabase.from('lojas').insert(lojas).select();
  if (lojaErr) { console.log("   ⚠️ Loja:", lojaErr.message); return; }
  const lojaId = lojaData[0].id;
  console.log(`   ✅ Loja criada ID: ${lojaId}`);

  // 2. Importar colaborador (Isabela)
  console.log("\n📥 Importando vendedora...");
  const { data: colabData, error: colabErr } = await supabase.from('colaboradores')
    .insert([{ ...colaboradores[0], loja_id: lojaId }]).select();
  if (colabErr) { console.log("   ⚠️ Colaborador:", colabErr.message); return; }
  const vendedorId = colabData[0].id;
  console.log(`   ✅ Vendedora Isabela ID: ${vendedorId}`);

  // 3. Importar clientes
  console.log(`\n📥 Importando ${clientes.length} clientes...`);
  let clientesImportados = 0;
  const clienteMap = new Map();
  
  for (const c of clientes) {
    const { data, error } = await supabase.from('clientes')
      .insert([{ ...c, loja_id: lojaId, status: 'Ativo' }])
      .select();
    if (data) {
      clientesImportados++;
      clienteMap.set(c.nome.toLowerCase(), data[0].id);
    }
  }
  console.log(`   ✅ ${clientesImportados} clientes importados`);

  // 4. Importar vendas
  console.log(`\n📥 Importando ${vendas.length} vendas...`);
  let vendasImportadas = 0;
  
  for (const v of vendas) {
    const clienteNome = v.cliente.toLowerCase();
    const clienteId = clienteMap.get(clienteNome) || null;
    
    const { data, error } = await supabase.from('vendas')
      .insert([{
        codigo: v.codigo,
        loja_id: lojaId,
        cliente_id: clienteId,
        vendedor_id: vendedorId,
        valor_total: v.valor,
        lucro_parcial: v.lucro,
        lucro_final: v.lucro,
        data_venda: '2026-07-10',
        situacao: 'Finalizada',
        tipo_pagamento: 'À Vista',
      }])
      .select();
    
    if (data) {
      vendasImportadas++;
      // Criar conta financeira automaticamente
      await supabase.from('contas_financeiro').insert([{
        loja_id: lojaId,
        tipo: 'Receber',
        descricao: `Venda #${v.codigo} - ${v.cliente}`,
        valor: v.valor,
        data_vencimento: '2026-07-10',
        pago: true,
        data_pagamento: '2026-07-10',
        categoria: 'Venda',
        referencia_id: data[0].id,
      }]);
    }
  }
  console.log(`   ✅ ${vendasImportadas} vendas importadas`);
  
  console.log("\n✅ Importação concluída com sucesso!");
  console.log(`   📊 ${clientesImportados} clientes`);
  console.log(`   💰 ${vendasImportadas} vendas`);
}

importar().catch(console.error);
